---
dagster_open_platform:
  target: "{{ env_var('DBT_TARGET', 'personal') }}"
  outputs:
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"

      user: "{{ env_var('SNOWFLAKE_DBT_USER', '') }}"
      password: "{{ env_var('SNOWFLAKE_DBT_PASSWORD', '') }}"

      role: "purina"
      database: "purina"
      warehouse: "purina"
      schema: "public"
      threads: 8
      client_session_keep_alive: false

    branch_deployment:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"

      user: "purina"
      password: "{{ env_var('SNOWFLAKE_DBT_PASSWORD', '') }}"

      role: "purina"
      database: "purina_clone_{{ env_var('DAGSTER_CLOUD_PULL_REQUEST_ID', '') }}"
      warehouse: "purina"
      schema: "public"
      threads: 8
      client_session_keep_alive: false

    ci:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"
      user: BUILDKITE_LINT
      password: "{{ env_var('SNOWFLAKE_BUILDKITE_LINT_PASSWORD', '') }}"
      database: purina
      warehouse: elementl
      schema: public

    personal:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"

      user: "{{ env_var('SNOWFLAKE_USER', '') }}"
      password: "{{ env_var('SNOWFLAKE_DBT_PASSWORD', '') }}"

      role: "{{ env_var('SNOWFLAKE_ROLE', '') }}"
      database: "sandbox"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'elementl') }}"
      schema: "{{ env_var('SNOWFLAKE_ROLE', '') }}"
      threads: 8
      client_session_keep_alive: false

    dogfood:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', '') }}"

      user: purina
      password: "{{ env_var('SNOWFLAKE_DBT_PASSWORD', '') }}"

      role: "purina"
      database: "dogfood_purina"
      warehouse: "purina"
      schema: "public"
      threads: 8
      client_session_keep_alive: false
